### ISSUE TITLE
Problem - SW 14 - x64

### ISSUE THREAD

**Issue by ghost** [nihilismus/bob-infinality-bundle#2]
Working on: /tmp/bob-infinality-bundle/fontconfig-2.11.1/doc/fontconfig-user.sgml
/usr/share/sgml/docbook/utils-0.6.14/backends/pdf: line 15: pdfjadetex: command not found
make[3]: **\* [fontconfig-user.pdf] Error 9
make[3]: Leaving directory `/tmp/bob-infinality-bundle/fontconfig-2.11.1/doc'
make[2]: *** [all] Error 2
make[2]: Leaving directory`/tmp/bob-infinality-bundle/fontconfig-2.11.1/doc'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/tmp/bob-infinality-bundle/fontconfig-2.11.1'
make: **\* [all] Error 2

**Comment by nihilismus** [comment]
`pdfjadetex` seems to be part of `t/tetex` package [1] in Slackware64. Install this package and try again.

[1] ftp://ftp.osuosl.org/pub/slackware/slackware64-current/source/t/tetex/
